### ISSUE TITLE
[Bug] CurrFieldNo global variable is readonly [still]

### ISSUE THREAD

**Issue by maksym-ch** [Microsoft/AL#4382]
The CurrFiledNo global variable is still read-only if it's assigned from table extension object.
The initial request https://github.com/Microsoft/AL/issues/4152

As was promised:
    **The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 26102.**

The mentioned bug still has not been fixed :-(

Tried on Microsoft Dynamiccs 365 Business Central Version 13.0.26413 (CU02)
Visual Studio Code Version 1.30.0
AL Language 2.1.73375.

During publishing I got the following warning (Package was published but needs to be installed):
[2018-12-19 08:32:28.19] The request for path /BC130/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: c:\ProgramData\Microsoft\Microsoft Dynamics NAV\130\Server\MicrosoftDynamicsNavServer$BC130\source\TableExtension\TableExtension50100.cs(128,17) : error CS0200: Property or indexer 'Microsoft.Dynamics.Nav.Runtime.Extensions.NavRecordExtension.CurrFieldNo' cannot be assigned to -- it is read only
During installation I got the following error:

![8ea04f2051ddff9220d1cc21bfac84428dfe71d0c04b67b36c pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/44081671/50216940-e5ac6d00-038f-11e9-98f7-6d5e852d1c87.png)

Could please check and fix it?

Thank you in advance

**Comment by JohanStenberg100** [comment]
Hi @maksym-ch, I'll look into this soon. Thanks for reporting this.

**Comment by JohanStenberg100** [comment]
@maksym-ch, I've verified this is working as expected on our master branch. You don't seem to use the docker image however (see "bcinsider.azurecr.io/bcsandbox-master Docker image"), so this is why it's not working for you.

**Comment by JohanStenberg100** [comment]
Also FYI, @maksym-ch, we are long overdue with taking a look at our versions and I apologize for the confusion this caused.

**Comment by maksym-ch** [comment]
@JohanStenberg100 , thank you for quick reply.
It works on 13.0.26685  build [insider docker]
Our customer wants to know when this fix will be included to release (CUXX)
Could you please inform me?
Please, do not close this ticket till its is released.

**Comment by JohanStenberg100** [comment]
Hi @maksym-ch, great to hear that you got it working! In this forum, we don't accept requests for adding bugfixes into cumulative updates. Please contact your regular support channel. You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours).
