### ISSUE TITLE
Dependencies Between Extensions don't work when "parent" field is referenced (2018 CU3)

### ISSUE THREAD

**Issue by jakubhojnacki** [Microsoft/AL#1995]
I know we are describing issue regarding NAV 2018 CU3, but it is very important for us to have it working for NAV we can deliver on-prem.
When we have two extensions with dependency - let's name them "parent" and "child" extension. When we reference any "parent" field anywhere in "child" tableextension or pageextension objects (whether it is a part of a FlowField added to "parent" table or page link used in action added to "parent" page), we can't deploy the "child" extension. 
VS Code doesn't flag any issues, symbols are all nicely visible, but when we try to deploy the "child" extension, that's what we get:
[2018-04-11 14:55:10.68] The request for path ... failed with code 422. Reason: Extension compilation failed
error AL0999: Internal error: 'One or more errors occurred.', Stack trace=unknown
When we remove offending property (making our "child" extension incomplete), everything works.
FlowField formulas and page links not using "parent" extension fields work fine.

**Comment by StanislawStempin** [comment]
Are you using the same version of the compiler in VS Code and on the server? See: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#which-version-of-the-al-language-extension-should-i-use

If you do and still hitting this issue could you give a short AL sample of what triggers the issue?

**Comment by jakubhojnacki** [comment]
We have tried the same scenario with AL add-in version 0.12.17720 (from NAV 2018 CU3 installation package) and the result was, unfortunately, exactly the same:
Microsoft (R) AL Compiler version 0.12.17720
error AL0999: Internal error: 'One or more errors occurred.', Stack trace=unknown
Error: The package could not be created.
Two add-ins code attached: "Item Class" is the "parent" one to be installed first and the "Item Sub-Class" is the "child" one referencing the "parent". The former installs and works perfectly, the latter - doesn't. We've marked crucial lines with //!!! comment (file "nHISC Item Class Extension.al" line 10 and "nHISC Item Classes Extension.al" line 23).
[Item Sub-Class.zip](https://github.com/Microsoft/AL/files/1901952/Item.Sub-Class.zip)
[Item Class.zip](https://github.com/Microsoft/AL/files/1901953/Item.Class.zip)

**Comment by Kraver88** [comment]
I have a similar issue:
A Parent extension has the table "ArtCasting Generic Type" which has Code and Type field. Type being an option.
The issue is when publishing the child extension who extends a table with a field related to a field in the parent extension:
![image](https://user-images.githubusercontent.com/24684493/38679301-ad9734a0-3e63-11e8-81d0-6fe50953708c.png)
This can be fixed by a small workaround by using the option id's instead of the actual value
![image](https://user-images.githubusercontent.com/24684493/38679370-dc2de994-3e63-11e8-9f27-e7fb8aff1976.png)

Only big problem I have with this is that for some reason he does not find the '0' option...
Hope this helps.

**Comment by Kraver88** [comment]
I get the same error when I try to subscribe to my Parent Publisher.

**Parent Publisher:**
[IntegrationEvent(false, false)]
    local procedure OnAfterCreateItem(var Item: Record Item);
    begin
    end;
**Child Subscriber**
    [EventSubscriber(ObjectType::Codeunit, 50000, 'OnAfterCreateItem', '', true, true)]
    local procedure Sub_OnAfterCreateItem_C50000(var Item: Record Item);
    begin
        message('test');
    end;
![image](https://user-images.githubusercontent.com/24684493/38685043-4fbd0c5c-3e71-11e8-9cfb-9455e073a1fd.png)

**Comment by jakubhojnacki** [comment]
I can confirm my scenario - "parent" table in extension 1 and "child" table in extension 2 - works fine with Dynamics NAV 2018 CU4, but only when using VS Code AL extension from 365 (version 0.15.18771). AL extension delivered with CU4 installation package (version 0.12.17720) still doesn't work.
Can we, please, sort it out 100%? It is almost done; thank you for your had work so far.

**Comment by jakubhojnacki** [comment]
We know now where the problem was. Basically:
- It has been fixed in 2018 CU5, so - please - use this version if you want it to work.
- It works only with matching Visual Studio Code AL extension (0.12.20065).
- Please, note,t he AL extension in the store is the Business Central one. You must install 0.12.20065 from a file you can find on the installation DVD or in "Modern Development Environment" subfolder of your NAV installation if you've installed the environment.
- The extension may have a problem stating a "Newtonsoft.Json" DLL file can't be found. If that's the case, please, have a look at issue [2165](https://github.com/Microsoft/AL/issues/2165) - there is a workaround described there.
