### ISSUE TITLE
Assembly not found

### ISSUE THREAD

**Issue by JeppeDueHansen** [microsoft/AL#5841]
**Describe the bug**
After upgrade to AL Language version 5.0, we are getting compilation errors on a few .NET assemblies:
        type(System.Array; SystemArray) { }
        type(System.Text.Encoding; SystemTxtEncoding) { }
        type(System.Convert; SystemConvert) { }

this worked in a previous version (version 4.0). If we downgrade the al language version to version 4.0, it works correctly again

**To Reproduce**
Steps and to reproduce the behavior:
add assembly probling path in VS code : 
c:/Windows/assembly/

``` AL Code to reproduce the issue ```
(In an AL file, add the following code)

dotnet
{
    assembly(System)
    {
        type(System.Array; SystemArray) { }
        type(System.Text.Encoding; SystemTxtEncoding) { }
        type(System.Convert; SystemConvert) { }
    }
}

**Expected behavior**
no problem in compiling

**Screenshots**
![image](https://user-images.githubusercontent.com/53214297/80377971-4446fc80-889c-11ea-90d2-9339863465bc.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: mcr.microsoft.com/businesscentral/onprem:15.1.37881.38071-w1

**Comment by KristofKlein** [comment]
Hi,

I had thisone as well (check: https://github.com/microsoft/AL/issues/5761 )

**Comment by thpeder** [comment]
Hi @JeppeDueHansen,
We have had bug fix in the compiler so the search for types works more deterministic now, that meant that types like SystemArray can't be found in System, but actually lives in System.Runtime as per [docs](https://docs.microsoft.com/en-us/dotnet/api/system.array?view=netcore-3.1)

**Comment by atoader** [comment]
After discussing this issue, we have concluded it is by design. See Thomas's comment above.
