### ISSUE TITLE
Publish-BcContainerApp throws an Internal Server Error

### ISSUE THREAD

**Issue by dsaveyn** [microsoft/AL#7095]
**Describe the issue**
We have a Sandbox with our AppSuite installed on it. The AppSuite consists out of 14 apps in total. 13 of them depend on a central Core App.

Version 20.0.6.118 of the Core App is published/installed. When we try to update it with Version 20.0.6.1905, using Publish-BCContainerApp, an Internal Server Error is thrown:

![image](https://user-images.githubusercontent.com/92365904/175893647-75d9cc89-993f-43ae-80f2-70dc69a1e74b.png)

We've looked into Application Insights but we cannot locate something useful (at first sight). What could be causing this issue?

Removing all 14 apps and increasing the version number again seems to fix the issue, but this should not be necessary.

I realize this issue is quite vague, but maybe some assistance/tips could guide us to the real cause of this problem.

**Scripts used to create container and cause the issue**
```
$RefreshToken = ''
$Environment = ''
$App = ''
$AuthContext = New-BcAuthContext -refreshToken $RefreshToken
Publish-BcContainerApp `
    -bcAuthContext $AuthContext `
    -environment $Environment `
    -appFile $App `
    -syncMode ForceSync 
```

**Full output of scripts**
```
2022-06-27T05:10:51.7733659Z BcContainerHelper version 3.0.4
2022-06-27T05:10:51.7804103Z BcContainerHelper emits usage statistics telemetry to Microsoft
2022-06-27T05:10:52.3812548Z WARNING: The names of some imported commands from the module 'BCContainerHelper' include unapproved verbs that might 
2022-06-27T05:10:52.3813262Z make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the 
2022-06-27T05:10:52.3814332Z Verbose parameter. For a list of approved verbs, type Get-Verb.
2022-06-27T05:10:52.3828414Z Sorting Apps
2022-06-27T05:10:58.6763506Z Retrieving Authentication Context
2022-06-27T05:10:58.7075962Z Attempting authentication to https://api.businesscentral.dynamics.com/user_impersonation offline_access using refresh token...
2022-06-27T05:10:58.8517637Z Authenticated using refresh token as user Director ESC Demo (director@demo365.esc.be)
2022-06-27T05:10:58.8635445Z Authenticated to common, using tenant id ***
2022-06-27T05:10:59.2834448Z Installing Dynavision_Dynavision Core_20.0.6.1905_sandbox_20.0_w1.app
2022-06-27T05:11:00.0012414Z Publishing Dynavision_Dynavision Core_20.0.6.1905_sandbox_20.0_w1.app to https://api.businesscentral.dynamics.com/v2.0/DynavisionTest/dev/apps?SchemaUpdateMode=forcesync
2022-06-27T05:11:02.4953867Z Publish-BcContainerApp Telemetry Correlation Id: 6e1f18d5-eb35-472c-bf2a-c11d59882d0a
2022-06-27T05:11:02.5368793Z Status Code InternalServerError : Internal Server Error
2022-06-27T05:11:02.5369434Z Object reference not set to an instance of an object.
2022-06-27T05:11:02.5370658Z At C:\Program Files\WindowsPowerShell\Modules\BCContainerHelper\3.0.4\AppHandling\Publish-NavContainerApp.ps1:254 
2022-06-27T05:11:02.5371484Z char:25
2022-06-27T05:11:02.5372182Z +                         throw $message
2022-06-27T05:11:02.5372702Z +                         ~~~~~~~~~~~~~~
2022-06-27T05:11:02.5373293Z     + CategoryInfo          : OperationStopped: (Status Code Int...e of an object.:String) [], RuntimeException
2022-06-27T05:11:02.5373968Z     + FullyQualifiedErrorId : Status Code InternalServerError : Internal Server Error
2022-06-27T05:11:02.5374530Z Object reference not set to an instance of an object.
2022-06-27T05:11:02.5374947Z  
2022-06-27T05:11:02.6177864Z ##[error]PowerShell exited with code '1'.
```

The App Files are build by our CI Pipelines using ALOps. Before we try to publish the apps, we check if the version is already installed via the Automation API's:

![image](https://user-images.githubusercontent.com/92365904/175895423-63a45bca-32e4-471b-9f2e-947e6d4b4f75.png)

If so, we don't publish the same version. 

Strangely, this used to work until last week. We haven't changed any Powershell code in the last month.

**Comment by pri-kise** [comment]
> Most of our procedures are set to internal and we use the InternalsVisibleTo property to make them visible to dependant apps
@dsaveyn mabye this results in differnt Object MetaData.
We had a similar issue 6 months ago, where we changed one procedure parameter of our own core app from passed by reference to passed by value (removing `var`). There we had to unpublish and re-publish the app or if the source code is included we could use `Repair-NavApp`.

**Comment by dsaveyn** [comment]
> > Most of our procedures are set to internal and we use the InternalsVisibleTo property to make them visible to dependant apps
> > @dsaveyn mabye this results in differnt Object MetaData.
> > We had a similar issue 6 months ago, where we changed one procedure parameter of our own core app from passed by reference to passed by value (removing `var`). There we had to unpublish and re-publish the app or if the source code is included we could use `Repair-NavApp`.

Yeah I'm thinking the same, issue is we are using an only sandbox so we can't use Repair-NavApp

**Comment by dsaveyn** [comment]
Same issue this morning. Our CD Pipeline fails with an Internal Server error. When I uninstall/unpublish all of our apps and do a publish we get a compilation error due do missing functions (even though we published the correct app just before that). Restarting the environment helped in this case.

On my development CDX I have the exact same thing this morning. I published our Core app followed by my dependent app and got this error (I've restarted the environment multiple times and republished both apps multiple times, same result):

![image](https://user-images.githubusercontent.com/92365904/176117914-9e8e87fb-eded-424d-a109-766961f50849.png)

**Comment by freddydk** [comment]
You will need to file a support ticket for the team to be able to investigate this.

QQ - can you repro this on a container?
Having two versions of your apps - deploy first version with -usedevendpoint and then deploy the next versions and get the same errors.

**Comment by dsaveyn** [comment]
I figured out the issue: 

Our core version was  20.0.6.XXX and the dependent app had the following in its app.json:

```
    {
      "id": "dbe4cf4c-5910-4ad1-beee-394010c59802",
      "name": "Dynavision Core",
      "publisher": "Dynavision",
      "version": "20.0.3.0"
    },
```

When I updated the version to 20.0.6.0 I was able to publish. This makes sense, but it wasn't necessary before, now it is. A clear error message would've helped a lot in this case. 

Strange thing is yesterday and even this morning I was able to publish both extensions multiple times on my Sandbox without adjusting any of the version numbers.

I can make a repro on a container, but with the above information I don't really think it's relevant anymore?

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
