### ISSUE TITLE
Extension Compilation failed with dependent extension in BC16.2

### ISSUE THREAD

**Issue by jayalakshmi0395** [microsoft/AL#5995]
I have a Code field "Purchase Request No." defined in a table extension against the Purchase Header table (Extension A).

Then I have created one more extension (Extension B) with dependent on Extension A (Specified the dependency in app.json) and downloaded symbols.

But unable to refer table extension fields from Extension A (Parent) in Extension B (Child). 

Error (AL0186)- A reference 'Purchase Request No.' in application object 'Purchase  Header' does not exist.
Error - Extension compilation failed.

Using Docker Image - mcr.microsoft.com/businesscentral/sandbox:ltsc2019
Works fine with docker 16.0 version. Getting this error in version 16.1 & 16.2.

**Versions:**
 - AL Language: v5.0.288712
 - Business Central: W1 16.2 (Platform 16.0.13440.13997 + Application 16.2.13509.14082)

**Comment by qutreson** [comment]
Hi @jayalakshmi0395 can you provide us with a project that reproduces the issue? (Including the packages for the dependencies of this project)

**Comment by fufikk** [comment]
Had a similar issue and managed to resolve it, perhaps it will work for you as well.
In both of my apps, the app.json specified the following:
```
"platform":  "16.0.0.0",
"application": "16.0.0.0"
```

I removed the application part and instead, put that in dependencies:
   ```
 {
      "id": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
      "publisher": "Microsoft",
      "name": "System Application",
      "version": "16.0.0.0"
    },
    {
      "id": "437dbf0e-84ff-417a-965d-ed2bb9650972",
      "publisher": "Microsoft",
      "name": "Base Application",
      "version": "16.0.0.0"
    }
```

Having done that, the apps were recompiled and published without an issue on 16.2.
I'm using:
-  the v5.0.288712 of AL Language,
- and for the container, the "new" approach with artifacts and here's my artifact url cmdlet: `Get-BcArtifactUrl -type OnPrem -country 'dk' -storageAccount 'bcartifacts' -version 16.2 -select Latest`

**Comment by atoader** [comment]
Can you provide a sample to reproduce the issue?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by jayalakshmi0395** [comment]
I have installed VMP365 app from App Source in my sandbox environment. I'm trying to extend this app.

For that i have created a new project. This is my app.json file.

`
{
  "id": "59777f92-1e66-45ec-9d11-0683e7397943",
  "name": "ALProject1",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [
    {
      "id": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
      "publisher": "Microsoft",
      "name": "System Application",
      "version": "16.0.0.0"
    },
    {
      "id": "437dbf0e-84ff-417a-965d-ed2bb9650972",
      "publisher": "Microsoft",
      "name": "Base Application",
      "version": "16.0.0.0"
    },
    {
      "id": "016ee7d8-b2a8-41b9-b90d-5e625d8c0d0c",
      "publisher": "CETAS Information Technology",
      "name": "CETAS VMP365",
      "version": "3.0.0.1"
    }
  ],
  "screenshots": [],
  "platform": "16.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "contextSensitiveHelpUrl": "https://ALProject1.com/help/",
  "showMyCode": true,
  "runtime": "5.0"
}
`

Downloaded symbols from sandbox environment. 

![image](https://user-images.githubusercontent.com/42033178/88366643-5525e200-cda7-11ea-8dd7-1a5e26c3b172.png)


Then I have created below table extension objects.

1. Extended a table from VMP365 App.

`
tableextension 50100 "TabExt Purch Req. Header" extends "CIT Purch Requisition Header"
{
    fields
    {
        field(50100; Remarks; Text[250])
        {
            DataClassification = OrganizationIdentifiableInformation;
        }
        field(50101; "Remarks 1"; Text[250])
        {
            DataClassification = OrganizationIdentifiableInformation;
        }

    }

}
`

2. Extended a default Purchase Header table.

`
tableextension 50101 "TabExt Purchase Header" extends "Purchase Header"
{
    fields
    {
        field(50100; Remarks; Text[250])
        {
            DataClassification = OrganizationIdentifiableInformation;
        }
        field(50101; "Remarks 1"; Text[250])
        {
            DataClassification = OrganizationIdentifiableInformation;
        }

    }

}
`

3. Created a new subscriber event.

`
codeunit 50100 "Purch. Req. Mgmnt"
{

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"CIT Vendor Portal", 'OnAfterInsertPurchHeadRFQ', '', false, false)]
    local procedure OnCreatePurchaseRFQHeader(var PurchaseRFQ: Record "Purchase Header"; PurchReqHeader: Record "CIT Purch Requisition Header")
    begin
        IF PurchaseRFQ."CIT Sub Document Type" <> PurchaseRFQ."CIT Sub Document Type"::RFQ then
            exit;

        PurchaseRFQ."Remarks" := PurchReqHeader.Remarks;
        PurchaseRFQ."Remarks 1" := PurchReqHeader."Remarks 1";
    end;
}
`

But I'm getting this error while referring VMP365 table extension fields.

![image](https://user-images.githubusercontent.com/42033178/88366557-1001b000-cda7-11ea-8393-0616f278b5a9.png)

Also tried to open the symbols using AL Object Designer and able to see the respective fields in Purchase Header table extension.
![image](https://user-images.githubusercontent.com/42033178/88366832-cf566680-cda7-11ea-90da-a93e595e1591.png)
